# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  types: [opened, edited, reopened, synchronize]
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
jobs:
  build:
    name: Build
    strategy:
      matrix:
        dotnet-version: ["8.0.x", "7.0.x", "6.0.x"]
        os: ["ubuntu-latest", "windows-latest"]
    runs-on: ${{matrix.os}}

  - uses: actions/checkout@v4
  name: Checkout
  with:
    fetch-depth: 0

- name: Setup dotnet ${{ matrix.dotnet-version }}
  uses: actions/setup-dotnet@v4
  with:
    dotnet-version: ${{ matrix.dotnet-version }}
    cache: true
    cache-dependency-path: "**/packages.lock.json"

   - name: Restore dependencies
  run: dotnet restore --no-cache --disable-parallel --verbosity minimal

    - name: Build
  run: dotnet build --configuration Release --no-restore
      
